# Generated by Django 5.2.8 on 2025-11-27 00:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('cobertura', models.CharField(choices=[('local', 'Local'), ('comunal', 'Comunal'), ('regional', 'Regional'), ('internacional', 'Internacional')], default='local', max_length=20, verbose_name='Zona de Cobertura')),
                ('whatsapp', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+56912345678'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='WhatsApp')),
                ('descripcion', models.TextField(verbose_name='Descripción del Negocio')),
                ('foto_empresa', models.ImageField(blank=True, null=True, upload_to='proveedores/fotos/', verbose_name='Foto de la Empresa')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('modo_oscuro', models.BooleanField(default=False, verbose_name='Modo Oscuro')),
                ('notif_email', models.BooleanField(default=True, verbose_name='Notificaciones por Email')),
                ('notif_mensajes', models.BooleanField(default=True, verbose_name='Notificaciones de Mensajes')),
                ('notif_pedidos', models.BooleanField(default=True, verbose_name='Notificaciones de Pedidos')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], default='es', max_length=10, verbose_name='Idioma')),
                ('zona_horaria', models.CharField(choices=[('America/Santiago', 'Santiago (Chile)'), ('America/Argentina/Buenos_Aires', 'Buenos Aires (Argentina)'), ('America/Sao_Paulo', 'São Paulo (Brasil)'), ('America/Lima', 'Lima (Perú)'), ('America/Bogota', 'Bogotá (Colombia)'), ('America/Mexico_City', 'Ciudad de México (México)')], default='America/Santiago', max_length=50, verbose_name='Zona Horaria')),
                ('perfil_publico', models.BooleanField(default=True, help_text='Si está desactivado, tu perfil no aparecerá en búsquedas públicas', verbose_name='Perfil Público')),
                ('mostrar_estadisticas', models.BooleanField(default=False, help_text='Mostrar número de visitas y contactos en tu perfil público', verbose_name='Mostrar Estadísticas Públicas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(related_name='proveedores', to='proveedor.categoria', verbose_name='Categorías')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.comuna', verbose_name='Comuna')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.pais', verbose_name='País')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Promoción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/', verbose_name='Imagen de la Promoción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='proveedor.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promocion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto/Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio_referencia', models.DecimalField(blank=True, decimal_places=2, help_text='Precio aproximado o de referencia', max_digits=10, null=True, verbose_name='Precio de Referencia')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('destacado', models.BooleanField(default=False, help_text='Destacar este producto en el perfil', verbose_name='Destacado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_servicios', to='proveedor.categoria', verbose_name='Categoría')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_servicios', to='proveedor.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto/Servicio',
                'verbose_name_plural': 'Productos/Servicios',
                'db_table': 'producto_servicio',
                'ordering': ['-destacado', '-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='proveedor.region'),
        ),
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='Mensaje de presentación', verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_contacto', to='proveedor.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Solicitud de Contacto',
                'verbose_name_plural': 'Solicitudes de Contacto',
                'db_table': 'solicitud_contacto',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
