# Generated by Django 5.2.8 on 2025-11-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='productoservicio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='region',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='region',
        ),
        migrations.AddField(
            model_name='productoservicio',
            name='categorias',
            field=models.CharField(choices=[('COM', 'Comidas'), ('BEB', 'Bebestibles'), ('SAL', 'Salud y Bienestar'), ('FER', 'Ferretería'), ('ABA', 'Abarrotes')], default='COM', max_length=40, verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comunas',
            field=models.CharField(choices=[('STG', 'Santiago'), ('LCN', 'Las Condes'), ('VMA', 'Viña del Mar'), ('CON', 'Concepción'), ('TEM', 'Temuco')], default='STG', max_length=40, verbose_name='Comunas'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='paises',
            field=models.CharField(choices=[('CL', 'Chile'), ('AR', 'Argentina'), ('PE', 'Perú'), ('CO', 'Colombia'), ('MX', 'México')], default='MX', max_length=40, verbose_name='Paises'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='regiones',
            field=models.CharField(choices=[('RM', 'Región Metropolitana'), ('VA', 'Valparaíso'), ('BI', 'Biobío'), ('AR', 'La Araucanía'), ('MA', 'Magallanes')], default='RM', max_length=40, verbose_name='Regiones'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cobertura',
            field=models.CharField(choices=[('local', 'Local'), ('comunal', 'Comunal'), ('regional', 'Regional'), ('internacional', 'Internacional')], default='local', max_length=40, verbose_name='Zona de Cobertura'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categorias',
            field=models.CharField(choices=[('COM', 'Comidas'), ('BEB', 'Bebestibles'), ('SAL', 'Salud y Bienestar'), ('FER', 'Ferretería'), ('ABA', 'Abarrotes')], default='COM', max_length=40, verbose_name='Categorias'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
