# Generated by Django 5.2.8 on 2025-11-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_proveedor_alter_comerciante_rol_alter_post_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comerciante',
            name='rol',
            field=models.CharField(choices=[('COMERCIANTE', 'Comerciante'), ('ADMIN', 'Administrador'), ('PROVEEDOR', 'Proveedor')], default='COMERCIANTE', help_text='Define si este usuario es comerciante o administrador del sistema.', max_length=20),
        ),
    ]
