# Generated by Django 5.2.5 on 2025-11-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_comerciante_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('DUDA', 'Duda / Pregunta'), ('OPINION', 'Opinión / Debate'), ('RECOMENDACION', 'Recomendación'), ('NOTICIA', 'Noticia del Sector'), ('GENERAL', 'General'), ('AYUDA_SOPORTE', 'Ayuda y Soporte'), ('GESTION_NEGOCIO', 'Gestión del Negocio'), ('MARKETING_VENTAS', 'Marketing y Ventas'), ('ATENCION_CLIENTE', 'Atención al Cliente'), ('TECNOLOGIA_COMERCIANTES', 'Tecnología para Comerciantes'), ('LEGAL_TRAMITES', 'Legal y Trámites'), ('INSPIRACION_EXITO', 'Inspiración y Casos de Éxito'), ('PROVEEDORES_ABASTO', 'Proveedores y Abastecimiento'), ('TENDENCIAS_COMERCIO', 'Tendencias del Comercio'), ('SALUD_EMPRENDEDOR', 'Salud del Emprendedor')], default='GENERAL', max_length=50, verbose_name='Categoría'),
        ),
    ]
