# Generated by Django 5.2.5 on 2025-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_post_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comerciante',
            name='intereses',
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='rol',
            field=models.CharField(choices=[('COMERCIANTE', 'Comerciante'), ('ADMIN', 'Administrador')], default='COMERCIANTE', max_length=15, verbose_name='Rol de Usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('DUDA', 'Duda / Pregunta'), ('OPINION', 'Opinión / Debate'), ('RECOMENDACION', 'Recomendación'), ('NOTICIA', 'Noticia del Sector'), ('GENERAL', 'General')], default='GENERAL', max_length=50, verbose_name='Categoría'),
        ),
    ]
