# Generated by Django 5.2.5 on 2025-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_comerciante_es_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comerciante',
            name='rol',
            field=models.CharField(choices=[('COMERCIANTE', 'Comerciante'), ('PROVEEDOR', 'Proveedor'), ('ADMIN', 'Administrador')], default='COMERCIANTE', max_length=15, verbose_name='Rol de Usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('NOTICIAS_CA', 'Noticias Club Almacén'), ('DESPACHOS', 'Despachos realizados'), ('NUEVOS_SOCIOS', 'Nuevos socios'), ('ACTIVIDADES', 'Actividades')], default='NOTICIAS_CA', max_length=50, verbose_name='Categoría'),
        ),
    ]
