# Generated by Django 5.2.5 on 2025-11-28 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_comerciante_intereses_alter_comerciante_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Asunto del Ticket')),
                ('categoria', models.CharField(choices=[('TECNICO', 'Fallo Técnico/Error'), ('PAGO', 'Consulta de Pago/Facturación'), ('SUGERENCIA', 'Sugerencia de Mejora'), ('OTRO', 'Otro/General')], max_length=20, verbose_name='Categoría')),
                ('comentario', models.TextField(verbose_name='Comentario y Detalles')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='tickets/', verbose_name='Foto/Archivo Adjunto')),
                ('contacto_opcional', models.CharField(blank=True, help_text='Opcional, para respuesta rápida fuera de la plataforma.', max_length=100, null=True, verbose_name='Contacto (Correo o Teléfono)')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('EN_PROCESO', 'En Proceso')], default='ABIERTO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.comerciante', verbose_name='Comerciante')),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
